name = "Fabric but Cool"
author = "AutiOne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3757387d21e574ac03f7db85eff5c35cbd0a5075016f3c19f7f2c4824a009191"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
